use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'DatabaseSyncRx' do
  pod 'RxDatabaseSync', :path => '../'
end

target 'DatabaseSyncRxTests' do
    inherit! :search_paths
    pod 'RxTest', '~> 3'
    pod 'RxDatabaseSync', :path => '../'
end

