author: RxDBSync
author_url: https://github.com/alobanov
github_url: https://github.com/alobanov/RxDBSync
module: RxDataBaseSyncDoc
xcodebuild_arguments: [-workspace,RxDataBaseSync.xcworkspace,-scheme,RxDataBaseSyncDoc]
output: docs
clean: true
skip_undocumented: false
min_acl: public
theme: apple
exclude:
- "**/JSONSerialization.swift"
- "**/EquatableHashableComparable.swift"
- "**/Utilities/*"
- "**/Extensions/*"
- "**/Clients/*"
- "**/Rx/*"
- "**/*.{h|m}"
- "**/Deprecated*"
- "**/UI/*"
- "**/*LocalizedStrings.swift"